// Use of variable in main.tf  

resource "local_file" "pet" {
    filename = var.filename
    content = var.content
}

resource "random_pet" "my-pet" {
  prefix = var.prefix
  separator = var.separator
  length = var.lenght
}
output "pet-name" {    // Out put variable
    value = random_pet.my-pet
    description = "Record the value of pet ID generated by the random_pet resource"
}